### ISSUE TITLE
Get DNS entry for GitHub pages

### ISSUE THREAD

**Issue by funnelfiasco** [ossf/security-baseline#82]
As part of #38, we'll need to request a DNS entry to use as a CNAME for the GitHub Pages version of the criteria. I propose `baseline.openssf.org`, but I'm open to other ideas as well.

Note to me: [custom domain docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)

**Comment by david-a-wheeler** [comment]
Just let me know what the domain name should be. It's not hard to set that up. See https://best.openssf.org for an example.

**Comment by funnelfiasco** [comment]
CNAME requested from OpenSSF Operations ([Slack](https://openssf.slack.com/archives/C05BETTLHEE/p1732638384890839))
