### ISSUE TITLE
[bug] build script does not check for invalid or duplicate IDs

### ISSUE THREAD

**Issue by funnelfiasco** [ossf/security-baseline#88]
The build script does not currently check to see if an ID appears twice or if an ID does not follow our defined format, which means we could end up re-using an ID by accident or adding an invalid ID.

I think the best way would be to add a `check` command that validates IDs (and possibly other fields), so that we can run just the `check` as a CI workflow on pull requests. The `compile` command, which produces actual output, could either call the check first, or we can adjust the pages workflow to include a validate step before the compile step as a backstop against something sneaking in accidentally.

**Comment by eddie-knight** [comment]
Related, possibly separate... we need to sort the entries according to category now that #87 is merged! Puerco and I noticed that it takes a bit of searching to make sure you're getting the right ID.

Also related, possibly separate... we should talk about (and document) what the project do with an ID in the event that an entry is deprecated or removed after an official release. It will be cumbersome to users if an ID is reused for a different entry.

**Comment by funnelfiasco** [comment]
Opened #94 and #96 for the points Eddie raised above.
