### ISSUE TITLE
Sort entries according to category

### ISSUE THREAD

**Issue by funnelfiasco** [ossf/security-baseline#94]
Mentioned by @eddie-knight in [issue 88](https://github.com/ossf/security-baseline/issues/88#issuecomment-2508663965):

> we need to sort the entries according to category now that https://github.com/ossf/security-baseline/pull/87 is merged! Puerco and I noticed that it takes a bit of searching to make sure you're using the right ID when making a new entry.

**Comment by funnelfiasco** [comment]
@eddie-knight did you mean in the file or in the output? I'm assuming in the file, but before I tackle this I want to make sure.

**Comment by eddie-knight** [comment]
Hey @funnelfiasco — I was working on this, but reviewing for typos got my eyes heavy 😆 Just opened the PR and linked it here

**Comment by funnelfiasco** [comment]
This was fixed in #95
